environments:
  default:
    values:
      - ../values.yaml
    secrets:
      - ../secrets.yaml
releases:
- name: doddns
  namespace: vpn
  createNamespace: true
  chart: charts/doddns
  values:
  - accessToken: {{ .Values.tls.digitalocean.accesstoken }}
    domain: {{ .Values.services.doddns.domain }}
    record: {{ .Values.services.doddns.record }}
- name: wireguard-as
  namespace: vpn
  chart: charts/wg-access-server
  values:
  - config:
      externalHost: {{ .Values.network.domain }}
      vpn:
        # allowedIPs:
        # - "{{ .Values.network.home_subnet }}/24, 192.168.0.1/32"
        cidr: {{ .Values.services.wireguard.vpn.cidr }}
      # dns:
      #   enabled: true
      #   upstream: {{ .Values.network.dns_ip }}
    wireguard:
      config:
        privateKey: {{ .Values.services.wireguard.privateKey }}
      service:
        type: LoadBalancer
        loadBalancerIP: {{ .Values.services.wireguard.ip }} 
    ingress:
      enabled: true
      hosts:
      - {{ .Values.services.wireguard.hostname }}
      tls:
      - secretName: {{ .Values.services.wireguard.hostname }}-tls
        hosts:
        - {{ .Values.services.wireguard.hostname }}
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
    persistence:
      enabled: true
      storageClass: {{ .Values.storage.storageClass }}
    web:
      config:
        adminPassword: {{ .Values.services.wireguard.adminPassword }}
