apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "static-site.fullname" . }}
  labels:
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
data:
  site.conf: |
  {{- .Values.siteConf  | nindent 4 }}