network:
  home_subnet: "192.168.1.0"
  vpn_subnet: "192.168.3.0"

  master_ip: "192.168.1.3"
  dns_ip: "192.168.1.3"
  gateway_ip: "192.168.1.1"
  
  domain: "home.dkuz.net"
  k8s_domain: "k8s.home.dkuz.net"
  metallb:
    default_range:
      start: "192.168.1.161"
      end: "192.168.1.200"
    reserved_range:
      start: "192.168.1.151"
      end: "192.168.1.160"
services:
  externaldns:
    ip: "192.168.1.153"
    port: 5300
    etcd:
      ip: "192.168.1.152"
  ingress:
    ip: "192.168.1.151"
  plex:
    ip: "192.168.1.154"
tls:
  issuer:
    name: letsencrypt-prod
storage:
  nodename: rocksteady
  server: rocksteady
  capacity: 4Ti
  mountpoint: /media/storage
env:
  timezone: "Asia/Jerusalem"
users:
  mediauser:
    uid: 2000
    gid: 2000
  janitor:
    uid: 1500
    gid: 1500
