network:
  home_subnet: "192.168.1.0"
  vpn_subnet: "192.168.3.0"

  master_ip: "192.168.1.3"
  dns_ip: "192.168.1.3"
  gateway_ip: "192.168.1.1"
  
  domain: "home.dkuz.net"
  k8s_domain: "k8s.home.dkuz.net"
  metallb:
    default_range:
      start: "192.168.1.171"
      end: "192.168.1.200"
    reserved_range:
      start: "192.168.1.151"
      end: "192.168.1.170"
services:
  externaldns:
    ip: "192.168.1.153"
    port: 5300
  ingress:
    ip: "192.168.1.151"
  plex:
    enabled: true
    ip: "192.168.1.154"
    hostname: "plex.media.k8s.home.dkuz.net"
  transmission:
    enabled: true
    hostname: "torrents.media.k8s.home.dkuz.net"
  jackett:
    enabled: true
    hostname: "indexer.media.k8s.home.dkuz.net"
  radarr:
    enabled: true
    hostname: "movies.media.k8s.home.dkuz.net"
  sonarr:
    enabled: true
    hostname: "tv.media.k8s.home.dkuz.net"
  bazarr:
    enabled: true
    hostname: "subs.media.k8s.home.dkuz.net"
  jellyfin:
    enabled: false
    hostname: "jellyfin.media.k8s.home.dkuz.net"
  nextcloud:
    enabled: false
    hostname: "nextcloud.k8s.home.dkuz.net"
  gallery:
    enabled: true
    hostname: "photos.k8s.home.dkuz.net"
  paperless:
    enabled: false
    hostname: "paperless.k8s.home.dkuz.net"
  doddns:
    enabled: true
    domain: dkuz.net
    record: home
  wireguard:
    enabled: true
    ip: "192.168.1.162"
    hostname: "vpn.k8s.home.dkuz.net"
    vpn:
      gw: "192.168.4.1"
      cidr: "192.168.4.0/24"
  docker_registry:
    enabled: false
    hostname: "registry.infra.k8s.home.dkuz.net"
  bookstack:
    enabled: true
    hostname: "wiki.k8s.home.dkuz.net"
tls:
  issuer:
    name: letsencrypt-prod
storage:
  nodename: nas
  server: nas.home.dkuz.net
  capacity: 4Ti
  storageClass: nfs-client
paths:
  root: /export/main

  # K8s
  volumes: /export/main/volumes

  # WWW
  gallery: /export/main/www/gallery

  # Media
  media: /export/main/media
  mediaConfig: /export/main/media/config

  # Files
  photos: /export/main/files/photos
  paperless: /export/main/files/paperless
  nextcloud: /export/main/files/nextcloud
  nextcloudRedis: /export/main/files/nextcloud-redis
  nextcloudMariadb: /export/main/files/nextcloud-mariadb
  bookstackMariadb: /export/main/files/bookstack-mariadb
  bookstackConfig: /export/main/files/bookstack-config

  # Infra
  dockerRegistry: /export/main/infra/docker-registry
  backupCache: /export/main/infra/backup-cache
env:
  timezone: "Asia/Jerusalem"
users:
  mediauser:
    uid: 2000
    gid: 2000