network:
  home_subnet: "192.168.1.0"
  vpn_subnet: "192.168.3.0"

  master_ip: "192.168.1.3"
  dns_ip: "192.168.1.3"
  gateway_ip: "192.168.1.1"
  
  domain: "home.dkuz.net"
  k8s_domain: "k8s.home.dkuz.net"
  metallb:
    default_range:
      start: "192.168.1.171"
      end: "192.168.1.200"
    reserved_range:
      start: "192.168.1.151"
      end: "192.168.1.170"
services:
  externaldns:
    ip: "192.168.1.153"
    port: 5300
  ingress:
    ip: "192.168.1.151"
  plex:
    ip: "192.168.1.154"
    hostname: "plex.media.k8s.home.dkuz.net"
  transmission:
    hostname: "torrents.media.k8s.home.dkuz.net"
  jackett:
    hostname: "indexer.media.k8s.home.dkuz.net"
  organizr:
    hostname: "dash.media.k8s.home.dkuz.net"
  radarr:
    hostname: "movies.media.k8s.home.dkuz.net"
  sonarr:
    hostname: "tv.media.k8s.home.dkuz.net"
  bazarr:
    hostname: "subs.media.k8s.home.dkuz.net"
  jellyfin:
    hostname: "jellyfin.media.k8s.home.dkuz.net"
  nextcloud:
    hostname: "nextcloud.k8s.home.dkuz.net"
  gallery:
    hostname: "photos.k8s.home.dkuz.net"
  paperless:
    hostname: "paperless.k8s.home.dkuz.net"
  doddns:
    domain: dkuz.net
    record: home
  wireguard:
    ip: "192.168.1.162"
    hostname: "vpn.k8s.home.dkuz.net"
    vpn:
      gw: "192.168.4.1"
      cidr: "192.168.4.0/24"
  docker_registry:
    hostname: "registry.infra.k8s.home.dkuz.net"
  recipes:
    hostname: "recipes.k8s.home.dkuz.net"
tls:
  issuer:
    name: letsencrypt-prod
storage:
  nodename: rocksteady
  server: rocksteady
  capacity: 4Ti
  storageClass: nfs-client
paths:
  root: /media/storage

  # K8s
  volumes: /media/storage/volumes

  # WWW
  gallery: /media/storage/www/gallery

  # Media
  media: /media/storage/media
  mediaConfig: /media/storage/media/config

  # Files
  photos: /media/storage/files/photos
  paperless: /media/storage/files/paperless
  nextcloud: /media/storage/files/nextcloud

  # Infra
  dockerRegistry: /media/storage/infra/docker-registry
  backupCache: /media/storage/infra/backup-cache
env:
  timezone: "Asia/Jerusalem"
users:
  mediauser:
    uid: 2000
    gid: 2000
  janitor:
    uid: 1500
    gid: 1500
