apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "doddns.fullname" . }}-files
  labels:
  labels:
    {{- include "doddns.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}

