replicaCount: 1

image:
  repository: linuxserver/plex
  tag: latest
  pullPolicy: Always

hostname: "GENERIC.local"
extraIP: ""
service:
  type: LoadBalancerIP
  port: 32400
  loadBalancerIP: ""
  externalTrafficPolicy: Local
probe:
  initialDelay: 40

env:
  uid: 0
  gid: 0
  timezone: UTC

pvc: ""
config:
  subpath: ""
data:
  subpath: ""
