apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restic-backup.fullname" . }}
  labels:
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
data:
  rclone.conf: |
    {{- .Values.rcloneConf  | nindent 4 }}
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}

