apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backup.fullname" . }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
type: Opaque
data:
  RESTIC_PASSWORD: "{{ .Values.resticPassword | b64enc }}"
  TELEGRAM_TOKEN: "{{ .Values.telegram.token  | b64enc }}"
  TELEGRAM_CLIENT: "{{ .Values.telegram.client | b64enc }}"
  {{- with .Values.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}