environments:
  default:
    values:
      - values.yaml
    secrets:
      - secrets.yaml

releases:
- name: coredns-configmap
  namespace: external-dns
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns-configmap
        labels:
          app: external-dns
      data:
        Corefile: |
          .:53 {
            errors
            health
            file /etc/coredns/zones/k8s_zone {{ .Values.network.k8s_domain }}
            proxy . /etc/resolv.conf
            loop
            reload
            loadbalance
          }
        k8s_zone: |
          $TTL 60
          $ORIGIN {{ .Values.network.k8s_domain }}.
          @         IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
                    2017042745 ; serial
                    7200       ; refresh (2 hours)
                    3600       ; retry (1 hour)			
                    1209600    ; expire (2 weeks)				
                    3600       ; minimum (1 hour)				
                    )
          @                                       IN A     {{ .Values.services.ingress.ip }}
          *.{{ .Values.network.k8s_domain }}.     IN A     {{ .Values.services.ingress.ip }}

          {{ .Values.services.transmission.hostname }}.     IN A     {{ .Values.services.transmission.ip }}
          {{ .Values.services.jackett.hostname }}.          IN A     {{ .Values.services.jackett.ip }}
          {{ .Values.services.organizr.hostname }}.         IN A     {{ .Values.services.organizr.ip }}
          {{ .Values.services.radarr.hostname }}.           IN A     {{ .Values.services.radarr.ip }}
          {{ .Values.services.sonarr.hostname }}.           IN A     {{ .Values.services.sonarr.ip }}
          {{ .Values.services.bazarr.hostname }}.           IN A     {{ .Values.services.bazarr.ip }}
          {{ .Values.services.plex.hostname }}.             IN A     {{ .Values.services.plex.ip }}
- name: coredns-service
  namespace: external-dns
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: Service
      metadata:
        name: coredns-lb
        annotations:
          metallb.universe.tf/allow-shared-ip: coredns-service
        labels:
          app: external-dns
      spec:
        type: LoadBalancer
        loadBalancerIP: {{ .Values.services.externaldns.ip }}
        ports:
          - name: dns
            port: {{ .Values.services.externaldns.port }}
            targetPort: 53
            protocol: UDP
        selector:
          app: external-dns
- name: coredns-deployment
  namespace: external-dns
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coredns
        labels:
          app: external-dns
      spec:
        progressDeadlineSeconds: 600
        revisionHistoryLimit: 10
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 1
          type: RollingUpdate
        replicas: 1
        selector:
          matchLabels:
            app: external-dns
        template:
          metadata:
            labels:
              app: external-dns
          spec:
            containers:
            - args:
              - -conf
              - /etc/coredns/Corefile
              image: coredns/coredns:1.3.1
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
              name: coredns-external
              ports:
              - containerPort: 53
                name: dns-udp
                protocol: UDP
              resources:
                limits:
                  memory: 170Mi
                requests:
                  cpu: 100m
                  memory: 70Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  add:
                  - NET_BIND_SERVICE
                  drop:
                  - all
                procMount: Default
                readOnlyRootFilesystem: true
              volumeMounts:
              - mountPath: /etc/coredns
                name: config-volume
                readOnly: true
            volumes:
            - configMap:
                name: coredns-configmap
                defaultMode: 420
                items:
                - key: Corefile
                  path: Corefile
                - key: k8s_zone
                  path: zones/k8s_zone
              name: config-volume
