environments:
  default:
    values:
      - values.yaml
    secrets:
      - secrets.yaml
releases:
# Volumes
- name: media-volumes
  namespace: media
  chart: incubator/raw
  values:
  - resources:
    # Host-local (faster) access
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: host-storage-vol
        labels:
          volume: host-storage-vol
      spec:
        capacity:
          storage: {{ .Values.storage.capacity }}
        volumeMode: Filesystem
        accessModes:
        - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        storageClassName: manual
        hostPath:
          path: {{ .Values.storage.mountpoint }}
          type: Directory
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.storage.nodename }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: host-storage-claim
      spec:
        storageClassName: manual
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: {{ .Values.storage.capacity }}
        selector:
          matchLabels:
            volume: host-storage-vol
    # NFS access
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: nfs-storage-vol
        labels:
          volume: nfs-storage-vol
      spec:
        capacity:
          storage: {{ .Values.storage.capacity }}
        volumeMode: Filesystem
        accessModes:
        - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        storageClassName: manual
        nfs:
          path: {{ .Values.storage.mountpoint }}
          server: {{ .Values.storage.server }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nfs-storage-claim
      spec:
        storageClassName: manual
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: {{ .Values.storage.capacity }}
        selector:
          matchLabels:
            volume: nfs-storage-vol
