environments:
  default:
    values:
      - values.yaml
    secrets:
      - secrets.yaml
releases:
# Transmission
# FIXME inject config with ConfigMap
- name: transmission
  namespace: media
  chart: charts/transmission
  values:
  - hostname: {{ .Values.services.transmission.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.transmission.ip }}
    storagetype: attached
    pvc: host-storage-claim
    config:
      subpath: ".config/transmission"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
    node: {{ .Values.storage.nodename }}
# Jackett
- name: jackett
  namespace: media
  chart: charts/genericc
  values:
  - image:
      repository: "linuxserver/jackett"
    hostname: {{ .Values.services.jackett.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.jackett.ip }}
      port: 9117
    storagetype: nfs
    pvc: nfs-storage-claim
    config:
      subpath: ".config/jackett"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
# Organizr
- name: organizr
  namespace: media
  chart: charts/genericc
  values:
  - image:
      repository: "linuxserver/organizr"
    hostname: {{ .Values.services.organizr.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.organizr.ip }}
      port: 80
    storagetype: nfs
    pvc: nfs-storage-claim
    config:
      subpath: ".config/organizr"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
# Radarr
- name: radarr
  namespace: media
  chart: charts/genericc
  values:
  - image:
      repository: "linuxserver/radarr"
    hostname: {{ .Values.services.radarr.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.radarr.ip }}
      port: 7878
    storagetype: nfs
    pvc: nfs-storage-claim
    config:
      subpath: ".config/radarr"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
# Sonarr
- name: sonarr
  namespace: media
  chart: charts/genericc
  values:
  - image:
      repository: "linuxserver/sonarr"
    hostname: {{ .Values.services.sonarr.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.sonarr.ip }}
      port: 8989
    storagetype: nfs
    pvc: nfs-storage-claim
    config:
      subpath: ".config/sonarr"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
# Bazarr
- name: bazarr
  namespace: media
  chart: charts/genericc
  values:
  - image:
      repository: "linuxserver/bazarr"
    hostname: {{ .Values.services.bazarr.hostname }}
    service:
      loadBalancerIP: {{ .Values.services.bazarr.ip }}
      port: 6767
    storagetype: nfs
    pvc: nfs-storage-claim
    config:
      subpath: ".config/bazarr"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
# Plex
- name: plex
  namespace: media
  chart: charts/plex
  values:
  - image:
      repository: "linuxserver/plex"
    hostname: {{ .Values.services.plex.hostname }}
    storagetype: attached
    pvc: host-storage-claim
    config:
      subpath: ".config/plex"
    env:
      timezone: {{ .Values.env.timezone }}
      uid: {{ .Values.users.mediauser.uid }}
      gid: {{ .Values.users.mediauser.gid }}
    service:
      type: LoadBalancer
      loadBalancerIP: {{ .Values.services.plex.ip }}
    extraIP: {{ .Values.services.plex.ip2 }}
