apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mount.fullname" . }}
  labels:
    {{- include "mount.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.capacity }}
  volumeMode: Filesystem
  accessModes:
  {{ toYaml .Values.accessModes | nindent 2}}
  persistentVolumeReclaimPolicy: {{ .Values.reclaimPolicy }}
  storageClassName: ""
  {{ toYaml .Values.driver | nindent 2 }}