environments:
  default:
    values:
      - ../values.yaml
    secrets:
      - ../secrets.yaml
releases:
- name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  chart: groundhog2k/mariadb
  values:
  - fullnameOverride: {{ .Values.name }}
    storage:
      requestedSize: 10Gi
{{- with .Values | get "storageClass" nil }}
      className: {{ . }}
{{- end }}
{{- with .Values | get "pvc" nil }}
      persistentVolumeClaimName: {{ . }}
{{- end }}
    settings:
      rootPassword: {{ .Values.rootPassword }} 
    userDatabase:
      name: {{ .Values.userDatabase }} 
      user: {{ .Values.userName }} 
      password: {{ .Values.userPassword }}