apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doclusterissuer.fullname" . }}
  labels:
    {{- include "doclusterissuer.labels" . | nindent 4 }}
type: Opaque
data:
  access-token: {{ .Values.digitalocean.accesstoken }}