environments:
  default:
    values:
      - ../values.yaml
    secrets:
      - ../secrets.yaml
helmfiles:
- path: common/servarr.yaml
  values:
  - name: sonarr
    hostname: {{ .Values.services.sonarr.hostname }}
    tag: preview
    volType: nfs
    enableMedia: true
- path: common/servarr.yaml
  values:
  - name: radarr
    hostname: {{ .Values.services.radarr.hostname }}
    tag: latest
    volType: nfs
    enableMedia: true
- path: common/servarr.yaml
  values:
  - name: bazarr
    hostname: {{ .Values.services.bazarr.hostname }}
    tag: latest
    volType: nfs
    enableMedia: true
- path: common/servarr.yaml
  values:
  - name: jackett
    hostname: {{ .Values.services.jackett.hostname }}
    tag: latest
    volType: nfs
    enableMedia: false
