environments:
  default:
    values:
      - ../values.yaml
    secrets:
      - ../secrets.yaml
releases:
- name: plex
  namespace: media
  chart: k8s-at-home/plex
  values:
  - claimToken: claim-xzsCtyMWdmBJxDGWoL6p
    image:
      repository: "linuxserver/plex"
      tag: latest
    allowedNetworks:
    - 127.0.0.1/8
    - 192.168.1.0/24
    - 10.42.0.0/16
    - 10.43.0.0/16
    plexUid: {{ .Values.users.mediauser.uid }}
    plexGid: {{ .Values.users.mediauser.gid }}
    timezone: {{ .Values.env.timezone }}
    serviceTCP:
      type: LoadBalancer
      nodePort: 32400
      loadBalancerIP: {{ .Values.services.plex.ip }}
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
      externalTrafficPolicy: Local
    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: {{ .Values.services.plex.ip }}
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
      - {{ .Values.services.plex.hostname }}
      tls:
      - secretName: "{{ .Values.services.plex.hostname }}-tls"
        hosts:
          - {{ .Values.services.plex.hostname }}
    persistence:
      config:
        claimName: plex-config
      data:
        enabled: false
      extraMounts:
      - name: media
        mountPath: /media/storage
        volume:
          persistentVolumeClaim:
            claimName: plex-media

helmfiles:
- path: common/servarr.yaml
  values:
  - name: jellyfin
    hostname: {{ .Values.services.jellyfin.hostname }}
    tag: latest
    volType: nfs
    enableMedia: true
- path: ../common/hostdir-mount.helmfile.yaml
  values:
  - namespace: media
    name: plex-config
    enable: true
    host: {{ .Values.storage.server }}
    path: "{{ .Values.paths.mediaConfig}}/plex"
- path: ../common/hostdir-mount.helmfile.yaml
  values:
  - namespace: media
    name: plex-media
    enable: true
    host: {{ .Values.storage.server }}
    path: "{{ .Values.paths.media }}"
  