apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        storagetype: {{ .Values.storagetype }}
      containers:
      - name: {{ .Release.Name }}-pod
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        - containerPort: 51413
          protocol: UDP
        - containerPort: 51413
          protocol: TCP
        env:
        - name: PUID
          value: "{{ .Values.env.uid }}"
        - name: PGID
          value: "{{ .Values.env.gid }}"
        - name: TZ
          value: {{ .Values.env.timezone }}
        livenessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.probe.initialDelay }}
          failureThreshold: 5
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /media/storage
          subPath: {{ .Values.data.subpath }}
        - name: {{ .Release.Name }}-vol
          mountPath: /config
          subPath: {{ .Values.config.subpath }}
      volumes:
      - name: {{ .Release.Name }}-vol
        persistentVolumeClaim:
          claimName: {{ .Values.pvc }}
