---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: {{ .Release.Name }}-lb
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
    app.kubernetes.io/component: controller
    release: nginx-ingress
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
