environments:
  default:
    values:
      - ../values.yaml
    secrets:
      - ../secrets.yaml
releases:
# - name: postgres
#   namespace: recipes
#   createNamespace: true
#   chart: groundhog2k/postgres
#   values:
#   - storage:
#       requestedSize: 10Gi
#       className: {{ .Values.storage.storageClass }}
#     settings:
#       superuserPassword: {{ .Values.services.recipes.postgres.superuserPassword }} 
#     userDatabase:
#       name: {{ .Values.services.recipes.postgres.userDatabase }} 
#       user: {{ .Values.services.recipes.postgres.userName }} 
#       password: {{ .Values.services.recipes.postgres.userPassword }} 
- name: recipes
  namespace: recipes
  createNamespace: true
  chart: k8s-at-home/recipes
  values:
  - env:
      TIMEZONE: {{ .Values.env.timezone }}
      # SECRET_KEY
      USERMAP_UID: {{ .Values.users.mediauser.uid }}
      USERMAP_FID: {{ .Values.users.mediauser.gid }}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: {{ .Values.services.recipes.postgres.userName }} 
      POSTGRES_DB: {{ .Values.services.recipes.postgres.userDatabase }} 
      POSTGRES_PASSWORD: {{ .Values.services.recipes.postgres.userPassword }} 
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: {{ .Values.services.recipes.hostname }}
          paths:
            - path: /
      tls:
      - secretName: {{ .Values.services.recipes.hostname }}-tls
        hosts:
          - {{ .Values.services.recipes.hostname }}