# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}
#   labels:
#     app: {{ .Chart.Name }}
#     release: {{ .Release.Name }}
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#   - port: {{ .Values.service.port }}
#     name: http
#     protocol: TCP
#   selector:
#     app: {{ .Chart.Name }}
#     release: {{ .Release.Name }}
#   externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    protocol: TCP
    nodePort: 32400
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
